repos:
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.15.0
    hooks:
    -   id: blacken-docs
        language_version: python3.8
        additional_dependencies:
        - black==22.12.0
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.8